move build checks to circleci and remove github action

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,12 +1,34 @@
 version: 2.1
 
 orbs:
-    doppler-circleci: ft-circleci-orbs/doppler-circleci@1.4
+  doppler-circleci: ft-circleci-orbs/doppler-circleci@1.4
 
 references:
   default_container_config: &default_container_config
     docker:
-      - image: cimg/node:lts
+      - image: cimg/node:20.7
+commands:
+  install_deps:
+    steps:
+      - run:
+          name: Install dependencies
+          command: npm ci
+
+  run_build:
+    steps:
+      - run:
+          name: Build
+          command: npm run build
+
+  assert_build:
+    steps:
+      - run:
+          name: Fail if build produces file changes to artifacts
+          command: |
+            if [ -n "$(git status --porcelain)" ]; then
+              echo "ERROR: spec and artifacts are out of sync. Please run build and commit."
+              exit 1
+            fi
 
 jobs:
   smoke-test:
@@ -26,7 +48,7 @@ jobs:
             node --test-reporter=tap --test-reporter-destination=./reports/test-report.txt --test-reporter=spec --test-reporter-destination=stdout --test libraries/from-bodyxml/smoke-test.js
       - run:
           name: Store test results and artifacts
-          command:  |
+          command: |
             cat ./reports/test-report.txt | npx tap-xunit > ./reports/test-report.xml
             exit 0
           when: always
@@ -35,12 +57,23 @@ jobs:
       - store_artifacts:
           path: ./reports
 
+  build-and-diff:
+    <<: *default_container_config
+    steps:
+      - checkout
+      - install_deps
+      - run_build
+      - assert_build
+
 workflows:
-  version: 2
+  verify-spec-and-artifacts:
+    jobs:
+      - build-and-diff
+
   hourly:
     triggers:
       - schedule:
-          cron: "5 * * * *"
+          cron: '5 * * * *'
           filters:
             branches:
               only:
